name: Continuous Integration
on: [push]
jobs:
  ci:
    name: Build, lint, and test with Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.x", "14.x", "16.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies with cache
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Build
        run: yarn build
