name: Deploy
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy Storybook, example, and coverage to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and combine files
        run: |
          yarn install
          yarn deploy

      - name: Deploy
        uses: jamesives/github-pages-deploy-action@v4
        with:
          folder: deploy
