name: Pull Request
on: [pull_request]
jobs:
  size:
    name: Comment with size-limit
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate sizes
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    name: Comment with Jest test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate coverage
        uses: artiomtr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: comment, report-markdown
          package-manager: yarn
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn run tsdx test --passWithNoTests
